version: '3'

services:
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager
    restart: always
    environment:
      DB_HOST: db
      DB_USER: npm
      DB_PASSWORD: npm
      DB_NAME: npm
    ports:
      - "80:80"
      - "443:443"
      - "81:81"
    depends_on:
      - db
    volumes:
      - npm_data:/data

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: npm
      MYSQL_USER: npm
      MYSQL_PASSWORD: npm
    volumes:
      - db_data:/var/lib/mysql

  portainer:
    image: portainer/portainer-ce
    restart: always
    ports:
      - "9000:9000"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  wordpress:
    image: wordpress
    restart: always
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: changeme
      WORDPRESS_DB_NAME: wordpress
    ports:
      - "8080:80"
    volumes:
      - wp_data:/var/www/html

  mariadb:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: changeme
    volumes:
      - wp_db:/var/lib/mysql

  watchdog:
    image: vishnunair/watchdog
    restart: always
    environment:
      WATCHDOG_TARGET: www.google.com
      WATCHDOG_INTERVAL: 60
    volumes:
      - watchdog_data:/data

  uptimekuma:
    image: uptimekuma/uptimekuma
    restart: always
    ports:
      - "3002:3000"
    environment:
      UPTIMEKUMA_API_USERNAME: admin
      UPTIMEKUMA_API_PASSWORD: changeme
    volumes:
      - uptimekuma_data:/app/data

  cloudflared:
    image: cloudflare/cloudflared
    restart: always
    command: tunnel
    environment:
      TUNNEL_HOSTNAME: example.com
      TUNNEL_URL: http://localhost:8080
    volumes:
      - cloudflared_data:/data

  heimdall:
    image: linuxserver/heimdall
    restart: always
    ports:
      - "3003:80"
    volumes:
      - heimdall_data:/config

  pi-hole:
    image: pihole/pihole
    restart: always
    environment:
      WEBPASSWORD: changeme
    ports:
      - "53:53/udp"
      - "85:80"
    dns:
      - 8.8.4.4
      - 8.8.8.8
    volumes:
      - pihole_data:/etc/pihole/
      - pihole_dnsmasq:/etc/dnsmasq.d/

  phpmyadmin:
    image: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mariadb
      PMA_USER: root
      PMA_PASSWORD: changeme
    ports:
      - "8081:80"

  duckdns:
    image: linuxserver/duckdns
    restart: always
    environment:
      TZ: "America/New_York"
      SUBDOMAINS: exampledomain
      TOKEN: changeme
    volumes:
      - duckdns_data:/config

  dozzle:
    image: amir20/dozzle
    restart: always
    ports:
      - "8082:8080/tcp"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  wireguard:
    image: linuxserver/wireguard
    restart: always
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/New_York
    ports:
      - "51820:51820/udp"
    volumes:
      - wireguard_data:/config

volumes:
  npm_data:
  db_data:
  wiki_data:
  wiki_customizations:
  pg_data:
  wp_data:
  wp_db:
  watchdog_data:
  uptimekuma_data:
  cloudflared_data:
  heimdall_data:
  pihole_data:
  pihole_dnsmasq:
  duckdns_data:
  wireguard_data:

